id: alien4cloud-deep-provider
name: Alien 4 Cloud - DEEP Provider
version: ${project.version}
description: Alien 4 Cloud Plugin Provider  for the DEEP Orchestrator
configuration_class: es.upv.indigodc.PluginConfiguration
#ui_entry_point: scripts/plugin.js
component_descriptors:
  - bean_name: orchestrator-factory
    name: DEEP Orchestrator
    description: Alien 4 Cloud Plugin Provider  for the DEEP Orchestrator
